#cloud-config
package_update: true
package_upgrade: true
package_reboot_if_required: true

manage-resolv-conf: true
resolv_conf:
  nameservers:
    - '8.8.8.8'
    - '8.8.4.4'

chpasswd:
  list: |
    root:${root_password}
  expire: False


packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg-agent
  - software-properties-common
  - zip
  - unzip

runcmd:
  - apt-get update -y
  - apt-get upgrade -y
  - apt-get autoremove -y
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
  - add-apt-repository "deb [arch=$(dpkg --print-architecture)] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - apt-get update -y
  - apt-get install -y docker-ce docker-ce-cli containerd.io
  - systemctl start docker
  - systemctl enable docker
  - curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  - chmod +x /usr/local/bin/docker-compose
  - wget https://github.com/jitsi/docker-jitsi-meet/archive/refs/tags/stable-6865.zip -O /opt/stable.zip
  - cd /opt
  - unzip stable.zip
  - mv ./docker-jitsi-meet-stable-6865 ./jitsi-meet
  - cd ./jitsi-meet
  - cp env.example .env
  - ./gen-passwords.sh
  - mkdir -p ~/.jitsi-meet-cfg/{web/crontabs,web/letsencrypt,transcripts,prosody/config,prosody/prosody-plugins-custom,jicofo,jvb,jigasi,jibri}
  - docker-compose up -d

final_message: "The system is finally up, after $UPTIME seconds"